#                                                            Developed by Acemix
#                                                      (Public repository on my GitHub)

name: TebexMessage

version: '0.0.1'
api-version: '1.20'

main: com.github.acemix.TebexMessage

commands:
  tebexmessage:
  tebexmessagereload: